language: node_js
node_js:
  - '8'

script:
  - yarn build

deploy:
  provider: s3
  access_key_id: ${ACCESS_KEY_ID}
  secret_access_key: ${SECRET_ACCESS_KEY}
  bucket: ${BUCKET_NAME}
  skip_cleanup: true
  local_dir: dist